package com.example.projemanag.utils

object Constants {

    const val USERS : String = "Users"
    const val IMAGE : String = "image"
    const val NAME : String = "name"
    const val MOBILE : String = "mobile"
    const val BOARDS : String = "boards"
    const val ASSIGNED_TO : String = "assignedTo"
    const val DOCUMENT_ID : String = "documentId"
    const val TASK_LIST : String = "taskList"
    const val CARDS : String = "cards"
    const val BOARD_DETAIL : String = "board_detail"
    const val ID : String = "id"
    const val email : String = "email"
    const val TASK_LIST_ITEM_POSITION : String = "task_list_item_position"
    const val CARD_LIST_ITEM_POSITION : String = "card_list_item_position"
    const val BOARD_MEMBERS_LIST : String = "board_members_list"
    const val SELECT : String = "Select"
    const val UN_SELECT : String = "UnSelect"
    const val PROGEMANAG_PREFERENCES: String = "ProjemanagPrefs"
    const val FCM_TOKEN:String = "fcmToken"
    const val FCM_TOKEN_UPDATED:String = "fcmTokenUpdated"
    const val FCM_BASE_URL:String = "https://fcm.googleapis.com/fcm/send"
    const val FCM_AUTHORIZATION:String = "authorization"
    const val FCM_KEY:String = "key"
    const val FCM_SERVER_KEY:String = "AAAAAT0TC94:APA91bEDCoY-d_6njALlxR3y69I3ro63j9wTrzUEpzEqjkgl8E8YVJs-_MQ4neIr8KLXx36EvC5rAHXjiRMxD8vfakCPMSTnLWW5gI85rcTr-7QjIZ67l8x6xrLWFd9Z-yQI5Uuu7pw9"
    const val FCM_KEY_TITLE:String = "title"
    const val FCM_KEY_MESSAGE:String = "message"
    const val FCM_KEY_DATA:String = "data"
    const val FCM_KEY_TO:String = "to"
}